[MODULES] Switch to Go Modules
terraform-providers/terraform-provider-rabbitmq pull request #26
Opened 2019-02-20 22:54 UTC by appilon

2019-02-21 16:34 UTC, radeksimko requested changes
One acceptance test is currently failing on this branch:

```
=== RUN   TestAccQueue_jsonArguments
--- FAIL: TestAccQueue_jsonArguments (0.14s)
    testing.go:538: Step 0 error: Check failed: resource not found: rabbitmq_queue.test
FAIL
```
I'm digging into this.

2019-02-21 18:39 UTC, radeksimko commented
I think I found the cause:
```
[ERR] Error writing fields: settings.0.arguments.x-message-ttl: '' expected type 'string', got unconvertible type 'float64'
```

2019-04-30 13:51 UTC, radeksimko approved these changes
This generally LGTM - thanks for chasing it down!

One major suggestion I would have though is to mark `arguments_json` as deprecated, so we can remove it in the future and more importantly make our intentions clear to the user.

2019-04-30 13:51 UTC, radeksimko commented on rabbitmq/resource_queue.go
> +							ValidateFunc:     validation.ValidateJsonString,
👍

2019-04-30 13:51 UTC, radeksimko commented on rabbitmq/resource_queue.go
> +	queue[0] = e
Nitpick: Do you mind moving the `queue` allocation here above this assignment, just so it's more/immediately obvious there's no risk in addressing the index like this as it is already allocated?

2019-04-30 14:21 UTC, appilon commented
@radeksimko I will address the allocation thing you mentioned. I think `arguments` would be deprecated as its likely unused in the wild since it cannot support non-string values? Could our decision to deprecate come in a separate PR?

2019-04-30 15:11 UTC, merged

2019-05-06 15:43 UTC, apparentlymart commented
Looking forward, I expect in the long run `arguments_json` is what would be deprecated and `arguments` would instead be defined as an arbitrary object rather than a map of string, once the SDK allows that. But as we currently stand, `arguments_json` does indeed seem to be the only way to define non-string arguments, and a string argument with a `_json` suffix is how we've worked around this in a number of other cases, so I think probably best for us to hold on deprecating anything for now until we're ready to address this via an SDK change.